# Server settings
server.port=8080

# MySQL connection settings
spring.datasource.url=jdbc:mysql://localhost:3306/bitstudent?useSSL=false
spring.datasource.username=root
spring.datasource.password=Rith-sql@2003
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# Database initialization
spring.jpa.hibernate.ddl-auto=update
hibernate.transaction.jta.platform=true
spring.jta.atomikos.properties.hibernate.transaction.jta.platform=com.atomikos.icatch.jta.hibernate4.AtomikosJtaPlatform